### PR TITLE
Make codebase Python 2 and 3 compatible

### PR DESCRIPTION
**Pull request by debugger22**
* Made changes to support Python 3
* Added dependency in setup.py
* Made some PEP8 changes

### CODE REVIEW

**Comment by debugger22** [comment]
Someone will have to manually test this PR. @bsmartt13 Please review.

**Comment by sebix** [comment]
- Why not use requests instead of old and dusty urllib?
- simplejson datetime, logger, re, time and urlparse are not used at all.
- identation contains tabs, that's not pep8
- lines are too long and old string formatting with `%` is used
- pulses in `getsince_iter` is never used.

**Comment by debugger22** [comment]
> Why not use requests instead of old and dusty urllib?

I think requests uses urllib internally. Anyway, adding an unnecessary dependency is not a good idea, IMO.

**Comment by debugger22** [comment]
@earada Thanks for merging!

**Comment by earada** [comment]
@debugger22 Thank you for the PR.

I'm agree with the *requests* dependency as well as the *simplejson* that we removed in this last commit. IMHO, the more we use from them included python libraries the easier will be for the users.

**Comment by sebix** [comment]
> > Why not use requests instead of old and dusty urllib?
> I think requests uses urllib internally. Anyway, adding an unnecessary dependency is not a good idea, IMO.

Yes. urllib is a low-level module and requests is high-level. Thus the API is more appropriate for daily high-level usage (which is nearly everything). E.g. this code:
```python
request = build_opener()
request.addheaders = [('X-OTX-API-KEY', self.key)]
response = None
try:
    response = request.open(url)
except URLError as e:
    if e.code == 403:
        raise InvalidAPIKey("Invalid API Key")
    elif e.code == 400:
        raise BadRequest("Bad Request")
data = response.read().decode()
json_data = json.loads(data)
```
becomes this:
```python
request = requests.get(url, headers={'X-OTX-API-KEY': self.key})
if request.status_code == 403:
    raise InvalidAPIKey("Invalid API Key")
elif requests.status_code == 400:
    raise BadRequest("Bad Request")
json_data = response.json
```
Also, en-/decoding and **certificate checking** is automatically done by the library. Otherwise, you have to do it yourself.

requests is installed on most Python installations anyway.

**Pull request merged**
