### PR TITLE
Fixes #30: API_V1_ROOT backslash

### LINKED ISSUE #30: API_V1_ROOT missing backslash causing requests to fail
API_V1_ROOT is `"api/v1"` when it looks like it should be `"/api/v1"` or requests to the API fail because `otx.alienvault.comapi` is not a valid hostname for HTTP requests. I'm on Python 2.7.11 just fyi.

- **Line:** https://github.com/AlienVault-Labs/OTX-Python-SDK/blob/master/OTXv2.py#L17

Simply prepending a backslash to the API_V1_ROOT variable fixed this for me when I reinstalled the latest master branch locally. Added the backslash to the line above, ran `pip install . --upgrade`, and it worked as expected.

**API call & Traceback:**
```
>>> mirai_iocs = otx.get_pulse_indicators('58e39804b789b25b15083fc6', limit=219)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    mirai_iocs = otx.get_pulse_indicators('58e39804b789b25b15083fc6', limit=219)
  File "/usr/local/lib/python2.7/site-packages/OTXv2.py", line 404, in get_pulse_indicators
    return self.walkapi(self.create_url(PULSE_DETAILS + str(pulse_id) + "/indicators", limit=limit))
  File "/usr/local/lib/python2.7/site-packages/OTXv2.py", line 274, in walkapi
    return list(self.walkapi_iter(url, max_page=max_page))
  File "/usr/local/lib/python2.7/site-packages/OTXv2.py", line 265, in walkapi_iter
    data = self.get(next_page_url)
  File "/usr/local/lib/python2.7/site-packages/OTXv2.py", line 112, in get
    proxies=self.proxies,
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='otx.alienvault.comapi', port=443): Max retries exceeded with url: /v1/pulses/58e39804b789b25b15083fc6/indicators?limit=219 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10c0d5110>: Failed to establish a new connection: [Errno 8] nodename nor servname provided
, or not known',))
```

As shown above the ConnectionError is failing due to `HTTPSConnectionPool(host='otx.alienvault.comapi', port=443)` where the host variable is not a valid hostname.

**After Patch:**
```
>>> from OTXv2 import OTXv2
>>> otx = OTXv2(key)
>>> mirai_iocs = otx.get_pulse_indicators('58e39804b789b25b15083fc6', limit=100)
>>> len(mirai_iocs)
100
```

### PR DESCRIPTION
**Pull request by deadbits**
- Adds backslash to https://github.com/AlienVault-Labs/OTX-Python-SDK/blob/master/OTXv2.py#L17
- Adds minor PEP fixes for over indentation of lines and whitespace after operators in a few spots

### CODE REVIEW

**Comment by deadbits** [comment]
Tests are failing due to missing `ALIEN_DEV_SERVER` the ci environment, I believe. If this can be added by a maintainer, or as @bsmartt13 said "if you make me a maintainer/collaborator on the github side, I can fix the build fail." :) 

If there is something I'm missing here with my related issue and this PR, any input would be great as well.

Relevant excerpts from CI failure:
- `requests.post(ALIEN_DEV_SERVER + 'otxapi/qatests/setup/', json={"users": [{ "username": username, "password": password, "email": email}]})`
- `requests.exceptions.MissingSchema: Invalid URL 'otxapi/qatests/setup/': No schema supplied. Perhaps you meant http://otxapi/qatests/setup/?`

**Comment by chrisdoman** [comment]
Thanks! I think there are a couple of other issues relating to test failures I need to review too

**Comment by deadbits** [comment]
Was Issue #30 a non-problem as well? Perhaps it's just my build for some reason, since I haven't seen anyone else mention problems with it, j/w if PR will be merged

**Comment by chrisdoman** [comment]
Yup it will be if I click the correct button this time :) Merging and will double check in a sec

**Comment by deadbits** [comment]
Thanks for the quick follow up! :D

**Pull request merged**
